--[[@class wayland_ffi]]
--[[@field wl_list_remove fun(list: wl_list)]]

--[[@class wl_resource]]
--[[@class wl_object]]
--[[@class wl_event_loop]]
--[[@class wl_global]]
--[[@class wl_event_source]]

--[[enums]]

--[[@class wl_data_device_error]]
--[[@class wl_display_error]]
--[[@class wl_keyboard_key_state]]
--[[@class wl_keyboard_keymap_format]]
--[[@class wl_output_mode]]
--[[@class wl_output_subpixel]]
--[[@class wl_output_transform]]
--[[@class wl_pointer_axis]]
--[[@class wl_pointer_button_state]]
--[[@class wl_pointer_error]]
--[[@class wl_seat_capability]]
--[[@class wl_shell_error]]
--[[@class wl_shell_surface_fullscreen_method]]
--[[@class wl_shell_surface_resize]]
--[[@class wl_shell_surface_transient]]
--[[@class wl_shm_error]]
--[[@class wl_shm_format]]
--[[@class wl_subcompositor_error]]
--[[@class wl_subsurface_error]]
--[[@class wl_surface_error]]
--[[@class wp_cursor_shape_device_v1_shape]]
--[[@class wl_data_device_manager_dnd_action]]
--[[@class wl_pointer_axis_source]]
--[[@class zwp_fullscreen_shell_v1_present_method]]
--[[@class zwlr_layer_surface_v1_keyboard_interactivity]]
--[[@class zwlr_layer_shell_v1_layer]]
--[[@class zwlr_output_power_v1_mode]]
--[[@class wl_pointer_axis_relative_direction]]
--[[@class zwp_pointer_constraints_v1_lifetime]]
--[[@class wp_tearing_control_v1_presentation_hint]]
--[[@class xdg_positioner_anchor]]
--[[@class xdg_positioner_gravity]]
--[[@class xdg_positioner_constraint_adjustment]]
--[[@class wl_iterator_result]]

--[[@alias wl_notify_func_t fun(listener: ptr_c<wl_listener>, data: ptr_c<unknown>)]]

--[[@class wl_message]]
--[[@field name string_c]]
--[[@field signature string_c]]
--[[@field types ptr_c<wl_interface>[] ]]

--[[@class wl_interface]]
--[[@field name string_c]]
--[[@field version integer]]
--[[@field method_count integer]]
--[[@field methods wl_message[] ]]
--[[@field event_count integer]]
--[[@field events wl_message[] ]]

--[[@class wl_list]]
--[[@field prev ptr_c<wl_list>]]
--[[@field next ptr_c<wl_list>]]

--[[@class wl_array]]
--[[@field size integer]]
--[[@field alloc integer]]
--[[@field data ptr_c<unknown>]]

--[[@class wl_argument union]]
--[[@field i integer]]
--[[@field u integer]]
--[[@field f integer fixed point int/256]]
--[[@field s string_c]]
--[[@field o ptr_c<wl_object>]]
--[[@field n integer]]
--[[@field a ptr_c<wl_array>]]
--[[@field h integer]]

--[[@class wl_listener]]
--[[@field link wl_list]]
--[[@field notify wl_notify_func_t]]

--[[@class wl_signal]]
--[[@field listener_list wl_list]]
