--[[@class pixman_region32_data_t]]

--[[@class pixman_box32_t]]
--[[@field x1 integer]]
--[[@field y1 integer]]
--[[@field x2 integer]]
--[[@field y2 integer]]

--[[@class pixman_region32_t]]
--[[@field extents pixman_box32_t]]
--[[@field data ptr_c<pixman_region32_data_t>]]

--[[@class wlr_box]]
--[[@field x integer]]
--[[@field y integer]]
--[[@field width integer]]
--[[@field height integer]]

--[[@class wlr_fbox]]
--[[@field x number]]
--[[@field y number]]
--[[@field width number]]
--[[@field height number]]

--[[@class wlr_scene_node_type enum]]
--[[@class wlr_scene_debug_damage_option enum]]

--[[@class wlr_scene_tree]]
--[[@field node wlr_scene_node]]
--[[@field children wl_list]]

--[[@class wlr_addon_set]]

--[[@class wlr_scene_node]]
--[[@field type wlr_scene_node_type]]
--[[@field parent ptr_c<wlr_scene_tree>]]
--[[@field link wl_list]]
--[[@field enabled boolean]]
--[[@field x integer]]
--[[@field y integer]]
--[[@field events wlr_scene_node_events]]
--[[@field data ptr_c<unknown>]]
--[[@field addons wlr_addon_set]]

--[[@class wlr_scene_node_events]]
--[[@field destroy wl_signal]]

--[[@class wlr_cursor_state]]

--[[@class wlr_cursor]]
--[[@field state ptr_c<wlr_cursor_state>]]
--[[@field x number]]
--[[@field y number]]
--[[@field events wlr_cursor_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_cursor_events]]
--[[@field motion wl_signal]]
--[[@field motion_absolute wl_signal]]
--[[@field button wl_signal]]
--[[@field axis wl_signal]]
--[[@field frame wl_signal]]
--[[@field swipe_begin wl_signal]]
--[[@field swipe_update wl_signal]]
--[[@field swipe_end wl_signal]]
--[[@field pinch_begin wl_signal]]
--[[@field pinch_update wl_signal]]
--[[@field pinch_end wl_signal]]
--[[@field hold_begin wl_signal]]
--[[@field hold_end wl_signal]]
--[[@field touch_up wl_signal]]
--[[@field touch_down wl_signal]]
--[[@field touch_motion wl_signal]]
--[[@field touch_cancel wl_signal]]
--[[@field touch_frame wl_signal]]
--[[@field tablet_tool_axis wl_signal]]
--[[@field tablet_tool_proximity wl_signal]]
--[[@field tablet_tool_tip wl_signal]]
--[[@field tablet_tool_button wl_signal]]

--[[@class wlr_output_state_field enum]]
--[[@class wl_output_transform enum]]
--[[@class wlr_output_state_mode_type enum]]

--[[@class wlr_output_state]]
--[[@field committed wlr_output_state_field]]
--[[@field allow_reconfiguration boolean]]
--[[@field damage pixman_region32_t]]
--[[@field enabled boolean]]
--[[@field scale number]]
--[[@field transform wl_output_transform]]
--[[@field adaptive_sync_enabled boolean]]
--[[@field render_format integer]]
--[[@field subpixel wl_output_subpixel]]
--[[@field buffer ptr_c<wlr_buffer>]]
--[[@field tearing_page_flip boolean]]
--[[@field mode_type wlr_output_state_mode_type]]
--[[@field mode ptr_c<wlr_output_mode>]]
--[[@field custom_mode wlr_output_custom_mode]]
--[[@field gamma_lut ptr_c<integer>]]
--[[@field gamma_lut_size integer]]
--[[@field layers ptr_c<wlr_output_layer_state>]]
--[[@field layers_len integer]]

--[[@class wlr_output_custom_mode]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field refresh integer]]

--[[@class wlr_output_impl]]
--[[@class wlr_render_pass]]

--[[@class wlr_output]]
--[[@field impl ptr_c<wlr_output_impl>]]
--[[@field backend ptr_c<wlr_backend>]]
--[[@field event_loop ptr_c<wl_event_loop>]]
--[[@field global ptr_c<wl_global>]]
--[[@field resources wl_list]]
--[[@field name string_c]]
--[[@field description ptr_c<integer>]]
--[[@field serial string_c]]
--[[@field make string_c]]
--[[@field model string_c]]
--[[@field phys_width integer]]
--[[@field phys_height integer]]
--[[@field modes wl_list]]
--[[@field current_mode ptr_c<wlr_output_mode>]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field refresh integer]]
--[[@field enabled boolean]]
--[[@field scale number]]
--[[@field subpixel wl_output_subpixel]]
--[[@field transform wl_output_transform]]
--[[@field adaptive_sync_status wlr_output_adaptive_sync_status]]
--[[@field render_format integer]]
--[[@field adaptive_sync_supported boolean]]
--[[@field needs_frame boolean]]
--[[@field frame_pending boolean]]
--[[@field non_desktop boolean]]
--[[@field commit_seq integer]]
--[[@field events wlr_output_events]]
--[[@field idle_frame ptr_c<wl_event_source>]]
--[[@field idle_done ptr_c<wl_event_source>]]
--[[@field attach_render_locks integer]]
--[[@field cursors wl_list]]
--[[@field hardware_cursor ptr_c<wlr_output_cursor>]]
--[[@field cursor_swapchain ptr_c<wlr_swapchain>]]
--[[@field cursor_front_buffer ptr_c<wlr_buffer>]]
--[[@field software_cursor_locks integer]]
--[[@field layers wl_list]]
--[[@field allocator ptr_c<wlr_allocator>]]
--[[@field renderer ptr_c<wlr_renderer>]]
--[[@field swapchain ptr_c<wlr_swapchain>]]
--[[@field display_destroy wl_listener]]
--[[@field addons wlr_addon_set]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_output_events]]
--[[@field frame wl_signal]]
--[[@field damage wl_signal]]
--[[@field needs_frame wl_signal]]
--[[@field precommit wl_signal]]
--[[@field commit wl_signal]]
--[[@field present wl_signal]]
--[[@field bind wl_signal]]
--[[@field description wl_signal]]
--[[@field request_state wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_output_event_damage]]
--[[@field output ptr_c<wlr_output>]]
--[[@field damage ptr_c<pixman_region32_t>]]

--[[@class wlr_output_present_flag enum]]

--[[@class wlr_output_event_precommit]]
--[[@field output ptr_c<wlr_output>]]
--[[@field when ptr_c<timespec>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_output_event_commit]]
--[[@field output ptr_c<wlr_output>]]
--[[@field when ptr_c<timespec>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_output_event_present]]
--[[@field output ptr_c<wlr_output>]]
--[[@field commit_seq integer]]
--[[@field presented boolean]]
--[[@field when ptr_c<timespec>]]
--[[@field seq integer]]
--[[@field refresh integer]]
--[[@field flags wlr_output_present_flag]]

--[[@class wlr_output_event_bind]]
--[[@field output ptr_c<wlr_output>]]
--[[@field resource ptr_c<wl_resource>]]

--[[@class wlr_output_event_request_state]]
--[[@field output ptr_c<wlr_output>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_pointer_impl]]

--[[@class wlr_pointer]]
--[[@field base wlr_input_device]]
--[[@field impl ptr_c<wlr_pointer_impl>]]
--[[@field output_name string_c]]
--[[@field events wl_pointer_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wl_pointer_events]]
--[[@field motion wl_signal]]
--[[@field motion_absolute wl_signal]]
--[[@field button wl_signal]]
--[[@field axis wl_signal]]
--[[@field frame wl_signal]]
--[[@field swipe_begin wl_signal]]
--[[@field swipe_update wl_signal]]
--[[@field swipe_end wl_signal]]
--[[@field pinch_begin wl_signal]]
--[[@field pinch_update wl_signal]]
--[[@field pinch_end wl_signal]]
--[[@field hold_begin wl_signal]]
--[[@field hold_end wl_signal]]

--[[@class wlr_pointer_motion_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field delta_x number]]
--[[@field delta_y number]]
--[[@field unaccel_dx number]]
--[[@field unaccel_dy number]]

--[[@class wlr_pointer_motion_absolute_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field x number]]
--[[@field y number]]

--[[@class wlr_pointer_button_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field button integer]]
--[[@field state wl_pointer_button_state]]

--[[@class wlr_pointer_axis_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field source wl_pointer_axis_source]]
--[[@field orientation wl_pointer_axis]]
--[[@field relative_direction wl_pointer_axis_relative_direction]]
--[[@field delta number]]
--[[@field delta_discrete integer]]

--[[@class wlr_pointer_swipe_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_swipe_update_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]
--[[@field dy number dx,]]

--[[@class wlr_pointer_swipe_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]

--[[@class wlr_pointer_pinch_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_pinch_update_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]
--[[@field dx number]]
--[[@field dy number]]
--[[@field scale number]]
--[[@field rotation number]]

--[[@class wlr_pointer_pinch_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]

--[[@class wlr_pointer_hold_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_hold_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]
