--[[@class pixman_region32_data_t]]

--[[@class pixman_box32_t]]
--[[@field x1 integer]]
--[[@field y1 integer]]
--[[@field x2 integer]]
--[[@field y2 integer]]

--[[@class pixman_region32_t]]
--[[@field extents pixman_box32_t]]
--[[@field data ptr_c<pixman_region32_data_t>]]

--[[@class wlr_box]]
--[[@field x integer]]
--[[@field y integer]]
--[[@field width integer]]
--[[@field height integer]]

--[[@class wlr_fbox]]
--[[@field x number]]
--[[@field y number]]
--[[@field width number]]
--[[@field height number]]

--[[@class wlr_scene_node_type enum]]
--[[@class wlr_scene_debug_damage_option enum]]

--[[@class wlr_scene_tree]]
--[[@field node wlr_scene_node]]
--[[@field children wl_list]]

--[[@class wlr_addon_set]]

--[[@class wlr_scene]]
--[[@field tree wlr_scene_tree]]
--[[@field outputs wl_list]]
--[[@field linux_dmabuf_v1 ptr_c<wlr_linux_dmabuf_v1>]]

--[[@class wlr_scene_node]]
--[[@field type wlr_scene_node_type]]
--[[@field parent ptr_c<wlr_scene_tree>]]
--[[@field link wl_list]]
--[[@field enabled boolean]]
--[[@field x integer]]
--[[@field y integer]]
--[[@field events wlr_scene_node_events]]
--[[@field data ptr_c<unknown>]]
--[[@field addons wlr_addon_set]]

--[[@class wlr_scene_node_events]]
--[[@field destroy wl_signal]]

--[[@class wl_keyboard_key_state enum]]

--[[@class wlr_keyboard_impl]]

--[[@class wlr_keyboard_modifiers]]
--[[@field depressed xkb_mod_mask_t]]
--[[@field latched xkb_mod_mask_t]]
--[[@field locked xkb_mod_mask_t]]
--[[@field group xkb_layout_index_t]]

--[[@class wlr_keyboard]]
--[[@field base wlr_input_device]]
--[[@field impl ptr_c<wlr_keyboard_impl>]]
--[[@field group ptr_c<wlr_keyboard_group>]]
--[[@field keymap_string string_c]]
--[[@field keymap_size integer]]
--[[@field keymap_fd integer]]
--[[@field keymap ptr_c<xkb_keymap>]]
--[[@field xkb_state ptr_c<xkb_state>]]
--[[@field led_indexes xkb_led_index_t[] ]]
--[[@field mod_indexes xkb_mod_index_t[] ]]
--[[@field leds integer]]
--[[@field keycodes integer[] ]]
--[[@field num_keycodes integer]]
--[[@field modifiers wlr_keyboard_modifiers]]
--[[@field repeat_info wlr_keyboard_repeat_info]]
--[[@field events wlr_keyboard_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_keyboard_events]]
--[[@field key wl_signal]]
--[[@field modifiers wl_signal]]
--[[@field keymap wl_signal]]
--[[@field repeat_info wl_signal]]

--[[@class wlr_keyboard_repeat_info]]
--[[@field rate integer]]
--[[@field delay integer]]

--[[@class wlr_keyboard_key_event]]
--[[@field time_msec integer]]
--[[@field keycode integer]]
--[[@field update_state boolean]]
--[[@field state wl_keyboard_key_state]]

--[[@class wlr_cursor_state]]

--[[@class wlr_cursor]]
--[[@field state ptr_c<wlr_cursor_state>]]
--[[@field x number]]
--[[@field y number]]
--[[@field events wlr_cursor_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_cursor_events]]
--[[@field motion wl_signal]]
--[[@field motion_absolute wl_signal]]
--[[@field button wl_signal]]
--[[@field axis wl_signal]]
--[[@field frame wl_signal]]
--[[@field swipe_begin wl_signal]]
--[[@field swipe_update wl_signal]]
--[[@field swipe_end wl_signal]]
--[[@field pinch_begin wl_signal]]
--[[@field pinch_update wl_signal]]
--[[@field pinch_end wl_signal]]
--[[@field hold_begin wl_signal]]
--[[@field hold_end wl_signal]]
--[[@field touch_up wl_signal]]
--[[@field touch_down wl_signal]]
--[[@field touch_motion wl_signal]]
--[[@field touch_cancel wl_signal]]
--[[@field touch_frame wl_signal]]
--[[@field tablet_tool_axis wl_signal]]
--[[@field tablet_tool_proximity wl_signal]]
--[[@field tablet_tool_tip wl_signal]]
--[[@field tablet_tool_button wl_signal]]

--[[@class wlr_output_state_field enum]]
--[[@class wl_output_transform enum]]
--[[@class wlr_output_state_mode_type enum]]

--[[@class wlr_output_state]]
--[[@field committed wlr_output_state_field]]
--[[@field allow_reconfiguration boolean]]
--[[@field damage pixman_region32_t]]
--[[@field enabled boolean]]
--[[@field scale number]]
--[[@field transform wl_output_transform]]
--[[@field adaptive_sync_enabled boolean]]
--[[@field render_format integer]]
--[[@field subpixel wl_output_subpixel]]
--[[@field buffer ptr_c<wlr_buffer>]]
--[[@field tearing_page_flip boolean]]
--[[@field mode_type wlr_output_state_mode_type]]
--[[@field mode ptr_c<wlr_output_mode>]]
--[[@field custom_mode wlr_output_custom_mode]]
--[[@field gamma_lut ptr_c<integer>]]
--[[@field gamma_lut_size integer]]
--[[@field layers ptr_c<wlr_output_layer_state>]]
--[[@field layers_len integer]]

--[[@class wlr_output_custom_mode]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field refresh integer]]

--[[@class wlr_output_impl]]
--[[@class wlr_render_pass]]

--[[@class wlr_output]]
--[[@field impl ptr_c<wlr_output_impl>]]
--[[@field backend ptr_c<wlr_backend>]]
--[[@field event_loop ptr_c<wl_event_loop>]]
--[[@field global ptr_c<wl_global>]]
--[[@field resources wl_list]]
--[[@field name string_c]]
--[[@field description ptr_c<integer>]]
--[[@field serial string_c]]
--[[@field make string_c]]
--[[@field model string_c]]
--[[@field phys_width integer]]
--[[@field phys_height integer]]
--[[@field modes wl_list]]
--[[@field current_mode ptr_c<wlr_output_mode>]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field refresh integer]]
--[[@field enabled boolean]]
--[[@field scale number]]
--[[@field subpixel wl_output_subpixel]]
--[[@field transform wl_output_transform]]
--[[@field adaptive_sync_status wlr_output_adaptive_sync_status]]
--[[@field render_format integer]]
--[[@field adaptive_sync_supported boolean]]
--[[@field needs_frame boolean]]
--[[@field frame_pending boolean]]
--[[@field non_desktop boolean]]
--[[@field commit_seq integer]]
--[[@field events wlr_output_events]]
--[[@field idle_frame ptr_c<wl_event_source>]]
--[[@field idle_done ptr_c<wl_event_source>]]
--[[@field attach_render_locks integer]]
--[[@field cursors wl_list]]
--[[@field hardware_cursor ptr_c<wlr_output_cursor>]]
--[[@field cursor_swapchain ptr_c<wlr_swapchain>]]
--[[@field cursor_front_buffer ptr_c<wlr_buffer>]]
--[[@field software_cursor_locks integer]]
--[[@field layers wl_list]]
--[[@field allocator ptr_c<wlr_allocator>]]
--[[@field renderer ptr_c<wlr_renderer>]]
--[[@field swapchain ptr_c<wlr_swapchain>]]
--[[@field display_destroy wl_listener]]
--[[@field addons wlr_addon_set]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_output_events]]
--[[@field frame wl_signal]]
--[[@field damage wl_signal]]
--[[@field needs_frame wl_signal]]
--[[@field precommit wl_signal]]
--[[@field commit wl_signal]]
--[[@field present wl_signal]]
--[[@field bind wl_signal]]
--[[@field description wl_signal]]
--[[@field request_state wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_output_event_damage]]
--[[@field output ptr_c<wlr_output>]]
--[[@field damage ptr_c<pixman_region32_t>]]

--[[@class wlr_output_present_flag enum]]

--[[@class wlr_output_event_precommit]]
--[[@field output ptr_c<wlr_output>]]
--[[@field when ptr_c<timespec>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_output_event_commit]]
--[[@field output ptr_c<wlr_output>]]
--[[@field when ptr_c<timespec>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_output_event_present]]
--[[@field output ptr_c<wlr_output>]]
--[[@field commit_seq integer]]
--[[@field presented boolean]]
--[[@field when ptr_c<timespec>]]
--[[@field seq integer]]
--[[@field refresh integer]]
--[[@field flags wlr_output_present_flag]]

--[[@class wlr_output_event_bind]]
--[[@field output ptr_c<wlr_output>]]
--[[@field resource ptr_c<wl_resource>]]

--[[@class wlr_output_event_request_state]]
--[[@field output ptr_c<wlr_output>]]
--[[@field state ptr_c<wlr_output_state>]]

--[[@class wlr_pointer_impl]]

--[[@class wlr_pointer]]
--[[@field base wlr_input_device]]
--[[@field impl ptr_c<wlr_pointer_impl>]]
--[[@field output_name string_c]]
--[[@field events wl_pointer_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wl_pointer_events]]
--[[@field motion wl_signal]]
--[[@field motion_absolute wl_signal]]
--[[@field button wl_signal]]
--[[@field axis wl_signal]]
--[[@field frame wl_signal]]
--[[@field swipe_begin wl_signal]]
--[[@field swipe_update wl_signal]]
--[[@field swipe_end wl_signal]]
--[[@field pinch_begin wl_signal]]
--[[@field pinch_update wl_signal]]
--[[@field pinch_end wl_signal]]
--[[@field hold_begin wl_signal]]
--[[@field hold_end wl_signal]]

--[[@class wlr_pointer_motion_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field delta_x number]]
--[[@field delta_y number]]
--[[@field unaccel_dx number]]
--[[@field unaccel_dy number]]

--[[@class wlr_pointer_motion_absolute_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field x number]]
--[[@field y number]]

--[[@class wlr_pointer_button_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field button integer]]
--[[@field state wl_pointer_button_state]]

--[[@class wlr_pointer_axis_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field source wl_pointer_axis_source]]
--[[@field orientation wl_pointer_axis]]
--[[@field relative_direction wl_pointer_axis_relative_direction]]
--[[@field delta number]]
--[[@field delta_discrete integer]]

--[[@class wlr_pointer_swipe_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_swipe_update_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]
--[[@field dy number dx,]]

--[[@class wlr_pointer_swipe_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]

--[[@class wlr_pointer_pinch_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_pinch_update_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]
--[[@field dx number]]
--[[@field dy number]]
--[[@field scale number]]
--[[@field rotation number]]

--[[@class wlr_pointer_pinch_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]

--[[@class wlr_pointer_hold_begin_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field fingers integer]]

--[[@class wlr_pointer_hold_end_event]]
--[[@field pointer ptr_c<wlr_pointer>]]
--[[@field time_msec integer]]
--[[@field cancelled boolean]]

--[[@class wlr_serial_range]]
--[[@field min_incl integer]]
--[[@field max_incl integer]]

--[[@class wlr_serial_ringset]]
--[[@field data ptr_c<wlr_serial_range>]]
--[[@field end integer]]
--[[@field count integer]]

--[[@class wlr_seat_client]]
--[[@field client ptr_c<wl_client>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field link wl_list]]
--[[@field resources wl_list]]
--[[@field pointers wl_list]]
--[[@field keyboards wl_list]]
--[[@field touches wl_list]]
--[[@field data_devices wl_list]]
--[[@field serials wlr_serial_ringset]]
--[[@field needs_touch_frame boolean]]
--[[@field value120 wlr_seat_client_value120]]

--[[@class wlr_seat_client_events]]
--[[@field destroy wl_signal]]

--[[@class wlr_seat_client_value120]]
--[[@field acc_discrete integer[] ]]
--[[@field last_discrete integer[] ]]
--[[@field acc_axis number[] ]]

--[[@class wlr_touch_point]]
--[[@field touch_id integer]]
--[[@field surface ptr_c<wlr_surface>]]
--[[@field client ptr_c<wlr_seat_client>]]
--[[@field focus_surface ptr_c<wlr_surface>]]
--[[@field focus_client ptr_c<wlr_seat_client>]]
--[[@field sx number]]
--[[@field sy number]]
--[[@field surface_destroy wl_listener]]
--[[@field focus_surface_destroy wl_listener]]
--[[@field client_destroy wl_listener]]
--[[@field events wlr_touch_point_events]]
--[[@field link wl_list]]

--[[@class wlr_touch_point_events]]
--[[@field destroy wl_signal]]

--[[@class wlr_pointer_grab_interface]]
--[[@field enter fun(grab: ptr_c<wlr_seat_pointer_grab>, surface: ptr_c<wlr_surface>, sx: number, sy: number)]]
--[[@field clear_focus fun(grab: ptr_c<wlr_seat_pointer_grab>)]]
--[[@field motion fun(grab: ptr_c<wlr_seat_pointer_grab>, time_msec: integer, sx: number, sy: number)]]
--[[@field button fun(grab: ptr_c<wlr_seat_pointer_grab>, time_msec: integer, button: integer, state: wl_pointer_button_state)]]
--[[@field axis	fun(grab: ptr_c<wlr_seat_pointer_grab>, time_msec: integer, orientation: wl_pointer_axis_relative_direction, value: number, value_discrete: integer, source: wl_pointer_axis_source, relative_direction: wl_pointer_axis_relative_direction)]]
--[[@field frame fun(grab: ptr_c<wlr_seat_pointer_grab>)]]
--[[@field cancel fun(grab: ptr_c<wlr_seat_pointer_grab>)]]

--[[@class wlr_keyboard_grab_interface]]
--[[@field enter fun(grab: ptr_c<wlr_seat_keyboard_grab>, surface: ptr_c<wlr_surface>, keycodes: integer[], num_keycodes: integer, modifiers: ptr_c<wlr_keyboard_modifiers>)]]
--[[@field clear_focus fun(grab: ptr_c<wlr_seat_keyboard_grab>)]]
--[[@field key fun(grab: ptr_c<wlr_seat_keyboard_grab>, time_msec: integer, key: integer, state: integer)]]
--[[@field modifiers fun(grab: ptr_c<wlr_seat_keyboard_grab>, modifiers: ptr_c<wlr_keyboard_modifiers>)]]
--[[@field cancel fun(grab: ptr_c<wlr_seat_keyboard_grab>)]]

--[[@class wlr_touch_grab_interface]]
--[[@field down fun(grab: ptr_c<wlr_seat_touch_grab>, time_msec: integer, point: ptr_c<wlr_touch_point>): integer]]
--[[@field up fun(grab: ptr_c<wlr_seat_touch_grab>, time_msec: integer, point: ptr_c<wlr_touch_point>): integer]]
--[[@field motion fun(grab: ptr_c<wlr_seat_touch_grab>, time_msec: integer, point: ptr_c<wlr_touch_point>)]]
--[[@field enter fun(grab: ptr_c<wlr_seat_touch_grab>, time_msec: integer, point: ptr_c<wlr_touch_point>)]]
--[[@field frame fun(grab: ptr_c<wlr_seat_touch_grab>)]]
--[[@field cancel fun(grab: ptr_c<wlr_seat_touch_grab>)]]
--[[@field wl_cancel fun(grab: ptr_c<wlr_seat_touch_grab>, seat_client: ptr_c<wlr_seat_client>)]]

--[[@class wlr_seat_touch_grab]]
--[[@field interface ptr_c<wlr_touch_grab_interface>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_seat_keyboard_grab]]
--[[@field interface ptr_c<wlr_keyboard_grab_interface>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_seat_pointer_grab]]
--[[@field interface ptr_c<wlr_pointer_grab_interface>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_seat_pointer_state]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field focused_client ptr_c<wlr_seat_client>]]
--[[@field focused_surface ptr_c<wlr_surface>]]
--[[@field sy number sx,]]
--[[@field grab ptr_c<wlr_seat_pointer_grab>]]
--[[@field default_grab ptr_c<wlr_seat_pointer_grab>]]
--[[@field sent_axis_source boolean]]
--[[@field cached_axis_source wl_pointer_axis_source]]
--[[@field buttons ptr_c<integer>]]
--[[@field button_count integer]]
--[[@field grab_button integer]]
--[[@field grab_serial integer]]
--[[@field grab_time integer]]
--[[@field surface_destroy wl_listener]]
--[[@field events wlr_seat_pointer_state_events]]

--[[@class wlr_seat_pointer_state_events]]
--[[@field focus_change wl_signal]]

--[[@class wlr_seat_keyboard_state]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field keyboard ptr_c<wlr_keyboard>]]
--[[@field focused_client ptr_c<wlr_seat_client>]]
--[[@field focused_surface ptr_c<wlr_surface>]]
--[[@field keyboard_destroy wl_listener]]
--[[@field keyboard_keymap wl_listener]]
--[[@field keyboard_repeat_info wl_listener]]
--[[@field surface_destroy wl_listener]]
--[[@field grab ptr_c<wlr_seat_keyboard_grab>]]
--[[@field default_grab ptr_c<wlr_seat_keyboard_grab>]]
--[[@field events wlr_seat_keyboard_state_events]]

--[[@class wlr_seat_keyboard_state_events]]
--[[@field focus_change wl_signal]]

--[[@class wlr_seat_touch_state]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field touch_points wl_list]]
--[[@field grab_serial integer]]
--[[@field grab_id integer]]
--[[@field grab ptr_c<wlr_seat_touch_grab>]]
--[[@field default_grab ptr_c<wlr_seat_touch_grab>]]

--[[@class wlr_primary_selection_source_impl]]

--[[@class wlr_primary_selection_source]]
--[[@field impl ptr_c<wlr_primary_selection_source_impl>]]
--[[@field  mime_types wl_array]]
--[[@field events wlr_primary_selection_source_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_primary_selection_source_events]]
--[[@field destroy wl_signal]]

--[[@class wlr_seat]]
--[[@field global ptr_c<wl_global>]]
--[[@field display ptr_c<wl_display>]]
--[[@field clients wl_list]]
--[[@field name string_c]]
--[[@field capabilities integer]]
--[[@field accumulated_capabilities integer]]
--[[@field last_event timespec]]
--[[@field selection_source ptr_c<wlr_data_source>]]
--[[@field selection_serial integer]]
--[[@field selection_offers wl_list]]
--[[@field primary_selection_source ptr_c<wlr_primary_selection_source>]]
--[[@field primary_selection_serial integer]]
--[[@field drag ptr_c<wlr_drag>]]
--[[@field drag_source ptr_c<wlr_data_source>]]
--[[@field drag_serial integer]]
--[[@field drag_offers wl_list]]
--[[@field pointer_state wlr_seat_pointer_state]]
--[[@field keyboard_state wlr_seat_keyboard_state]]
--[[@field touch_state wlr_seat_touch_state]]
--[[@field display_destroy wl_listener]]
--[[@field selection_source_destroy wl_listener]]
--[[@field primary_selection_source_destroy wl_listener]]
--[[@field drag_source_destroy wl_listener]]
--[[@field events wl_seat_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wl_seat_events]]
--[[@field pointer_grab_begin wl_signal]]
--[[@field pointer_grab_end wl_signal]]
--[[@field keyboard_grab_begin wl_signal]]
--[[@field keyboard_grab_end wl_signal]]
--[[@field touch_grab_begin wl_signal]]
--[[@field touch_grab_end wl_signal]]
--[[@field request_set_cursor wl_signal]]
--[[@field request_set_selection wl_signal]]
--[[@field set_selection wl_signal]]
--[[@field request_set_primary_selection wl_signal]]
--[[@field set_primary_selection wl_signal]]
--[[@field request_start_drag wl_signal]]
--[[@field start_drag wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_seat_pointer_request_set_cursor_event]]
--[[@field seat_client ptr_c<wlr_seat_client>]]
--[[@field surface ptr_c<wlr_surface>]]
--[[@field serial integer]]
--[[@field hotspot_x integer]]
--[[@field hotspot_y integer]]

--[[@class wlr_seat_request_set_selection_event]]
--[[@field source ptr_c<wlr_data_source>]]
--[[@field serial integer]]

--[[@class wlr_seat_request_set_primary_selection_event]]
--[[@field source ptr_c<wlr_primary_selection_source>]]
--[[@field serial integer]]

--[[@class wlr_seat_request_start_drag_event]]
--[[@field drag ptr_c<wlr_drag>]]
--[[@field origin ptr_c<wlr_surface>]]
--[[@field serial integer]]

--[[@class wlr_seat_pointer_focus_change_event]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field old_surface ptr_c<wlr_surface>]]
--[[@field new_surface ptr_c<wlr_surface>]]
--[[@field sx number]]
--[[@field sy number]]

--[[@class wlr_seat_keyboard_focus_change_event]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field old_surface ptr_c<wlr_surface>]]
--[[@field new_surface ptr_c<wlr_surface>]]

--[[@class wlr_surface_state_field enum]]

--[[@class wlr_surface_state]]
--[[@field committed wlr_surface_state_field]]
--[[@field seq integer]]
--[[@field buffer ptr_c<wlr_buffer>]]
--[[@field dx integer]]
--[[@field dy integer]]
--[[@field surface_damage pixman_region32_t]]
--[[@field buffer_damage pixman_region32_t]]
--[[@field opaque pixman_region32_t]]
--[[@field input pixman_region32_t]]
--[[@field transform wl_output_transform]]
--[[@field scale integer]]
--[[@field frame_callback_list wl_list]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field buffer_width integer]]
--[[@field buffer_height integer]]
--[[@field subsurfaces_below wl_list]]
--[[@field subsurfaces_above wl_list]]
--[[@field viewport wlr_surface_state_viewport]]
--[[@field cached_state_locks integer]]
--[[@field cached_state_link wl_list]]
--[[@field synced wl_array]]

--[[@class wlr_surface_state_viewport]]
--[[@field has_src boolean]]
--[[@field has_dst boolean]]
--[[@field src wlr_fbox]]
--[[@field dst_width integer]]
--[[@field dst_height integer]]

--[[@class wlr_surface_role]]
--[[@field name string_c]]
--[[@field no_object boolean]]
--[[@field client_commit fun(surface: ptr_c<wlr_surface>)]]
--[[@field commit fun(surface: ptr_c<wlr_surface>)]]
--[[@field unmap fun(surface: ptr_c<wlr_surface>)]]
--[[@field destroy fun(surface: ptr_c<wlr_surface>)]]

--[[@class wlr_surface_output]]
--[[@field surface ptr_c<wlr_surface>]]
--[[@field output ptr_c<wlr_output>]]
--[[@field link wl_list]]
--[[@field bind wl_listener]]
--[[@field destroy wl_listener]]

--[[@class wlr_surface]]
--[[@field resource ptr_c<wl_resource>]]
--[[@field compositor ptr_c<wlr_compositor>]]
--[[@field buffer ptr_c<wlr_client_buffer>]]
--[[@field buffer_damage pixman_region32_t]]
--[[@field opaque_region pixman_region32_t]]
--[[@field input_region pixman_region32_t]]
--[[@field current wlr_surface_state]]
--[[@field pending wlr_surface_state]]
--[[@field cached wl_list]]
--[[@field mapped boolean]]
--[[@field role ptr_c<wlr_surface_role>]]
--[[@field role_resource ptr_c<wl_resource>]]
--[[@field events wlr_surface_events]]
--[[@field current_outputs wl_list]]
--[[@field addons wlr_addon_set]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_surface_events]]
--[[@field client_commit wl_signal]]
--[[@field commit wl_signal]]
--[[@field map wl_signal]]
--[[@field unmap wl_signal]]
--[[@field new_subsurface wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_compositor]]
--[[@field global ptr_c<wl_global>]]
--[[@field renderer ptr_c<wlr_renderer>]]
--[[@field display_destroy wl_listener]]
--[[@field renderer_destroy wl_listener]]
--[[@field events wlr_compositor_events]]

--[[@class wlr_compositor_events]]
--[[@field new_surface wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_renderer]]
--[[@field render_buffer_caps integer]]
--[[@field events wlr_renderer_events]]
--[[@field features wlr_renderer_features]]

--[[@class wlr_renderer_events]]
--[[@field destroy wl_signal]]
--[[@field lost wl_signal]]

--[[@class wlr_renderer_features]]
--[[@field output_color_transform boolean]]

--[[@class wlr_xdg_shell]]
--[[@field global ptr_c<wl_global>]]
--[[@field version integer]]
--[[@field clients wl_list]]
--[[@field popup_grabs wl_list]]
--[[@field ping_timeout integer]]
--[[@field display_destroy wl_listener]]
--[[@field events wlr_xdg_shell_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_xdg_shell_events]]
--[[@field new_surface wl_signal]]
--[[@field new_toplevel wl_signal]]
--[[@field new_popup wl_signal]]
--[[@field destroy wl_signal]]

--[[@class wlr_edges enum]]
--[[@class wlr_xdg_surface_role enum]]
--[[@class wlr_xdg_toplevel_wm_capabilities enum]]
--[[@class wlr_xdg_toplevel_configure_field enum]]

--[[@class wlr_xdg_toplevel_state]]
--[[@field maximized boolean]]
--[[@field fullscreen boolean]]
--[[@field resizing boolean]]
--[[@field activated boolean]]
--[[@field suspended boolean]]
--[[@field tiled wlr_edges]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field max_width integer]]
--[[@field max_height integer]]
--[[@field min_width integer]]
--[[@field min_height integer]]

--[[@class wlr_xdg_toplevel_configure]]
--[[@field fields wlr_xdg_toplevel_configure_field]]
--[[@field maximized boolean]]
--[[@field fullscreen boolean]]
--[[@field resizing boolean]]
--[[@field activated boolean]]
--[[@field suspended boolean]]
--[[@field tiled wlr_edges]]
--[[@field width integer]]
--[[@field height integer]]
--[[@field bounds wlr_xdg_toplevel_configure_bounds]]
--[[@field wm_capabilities wlr_xdg_toplevel_wm_capabilities]]

--[[@class wlr_xdg_toplevel_configure_bounds]]
--[[@field width integer]]
--[[@field height integer]]

--[[@class wlr_xdg_toplevel_requested]]
--[[@field maximized boolean]]
--[[@field minimized boolean]]
--[[@field fullscreen boolean]]
--[[@field fullscreen_output ptr_c<wlr_output>]]
--[[@field fullscreen_output_destroy wl_listener]]

--[[@class wlr_xdg_toplevel]]
--[[@field resource ptr_c<wl_resource>]]
--[[@field base ptr_c<wlr_xdg_surface>]]
--[[@field parent ptr_c<wlr_xdg_toplevel>]]
--[[@field parent_unmap wl_listener]]
--[[@field current wlr_xdg_toplevel_state]]
--[[@field pending wlr_xdg_toplevel_state]]
--[[@field scheduled wlr_xdg_toplevel_configure]]
--[[@field requested wlr_xdg_toplevel_requested]]
--[[@field title string_c]]
--[[@field app_id string_c]]
--[[@field events wlr_xdg_toplevel_events]]

--[[@class wlr_xdg_toplevel_events]]
--[[@field destroy wl_signal]]
--[[@field request_maximize wl_signal]]
--[[@field request_fullscreen wl_signal]]
--[[@field request_minimize wl_signal]]
--[[@field request_move wl_signal]]
--[[@field request_resize wl_signal]]
--[[@field request_show_window_menu wl_signal]]
--[[@field set_parent wl_signal]]
--[[@field set_title wl_signal]]
--[[@field set_app_id wl_signal]]

--[[@class wlr_xdg_surface_state]]
--[[@field configure_serial integer]]
--[[@field geometry wlr_box]]

--[[@class wlr_xdg_surface]]
--[[@field client ptr_c<wlr_xdg_client>]]
--[[@field resource ptr_c<wl_resource>]]
--[[@field surface ptr_c<wlr_surface>]]
--[[@field link wl_list]]
--[[@field role wlr_xdg_surface_role]]
--[[@field role_resource ptr_c<wl_resource>]]
--[[@field toplevel ptr_c<wlr_xdg_toplevel> union]]
--[[@field popup ptr_c<wlr_xdg_popup> union]]
--[[@field popups wl_list]]
--[[@field configured boolean]]
--[[@field configure_idle ptr_c<wl_event_source>]]
--[[@field scheduled_serial integer]]
--[[@field configure_list wl_list]]
--[[@field pending wlr_xdg_surface_state current,]]
--[[@field initialized boolean]]
--[[@field initial_commit boolean]]
--[[@field events wlr_xdg_surface_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_xdg_surface_events]]
--[[@field destroy wl_signal]]
--[[@field ping_timeout wl_signal]]
--[[@field new_popup wl_signal]]
--[[@field configure wl_signal]]
--[[@field ack_configure wl_signal]]

--[[@class wlr_xdg_toplevel_move_event]]
--[[@field toplevel ptr_c<wlr_xdg_toplevel>]]
--[[@field seat ptr_c<wlr_seat_client>]]
--[[@field serial integer]]

--[[@class wlr_xdg_toplevel_resize_event]]
--[[@field toplevel ptr_c<wlr_xdg_toplevel>]]
--[[@field seat ptr_c<wlr_seat_client>]]
--[[@field serial integer]]
--[[@field edges integer]]

--[[@class wlr_xdg_toplevel_show_window_menu_event]]
--[[@field toplevel ptr_c<wlr_xdg_toplevel>]]
--[[@field seat ptr_c<wlr_seat_client>]]
--[[@field serial integer]]
--[[@field x integer]]
--[[@field y integer]]

--[[@class wlr_xdg_popup]]
--[[@field base ptr_c<wlr_xdg_surface>]]
--[[@field link wl_list]]
--[[@field resource ptr_c<wl_resource>]]
--[[@field parent ptr_c<wlr_surface>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field scheduled wlr_xdg_popup_configure]]
--[[@field current wlr_xdg_popup_state]]
--[[@field pending wlr_xdg_popup_state]]
--[[@field events wlr_xdg_popup_events]]
--[[@field grab_link wl_list]]

--[[@class wlr_xdg_popup_events]]
--[[@field destroy wl_signal]]
--[[@field reposition wl_signal]]

--[[@class wlr_backend_impl]]

--[[@class wlr_backend]]
--[[@field impl ptr_c<wlr_backend_impl>]]
--[[@field events wlr_backend_events]]

--[[@class wlr_backend_events]]
--[[@field destroy wl_signal]]
--[[@field new_input wl_signal]]
--[[@field new_output wl_signal]]

--[[@class wlr_xwayland]]
--[[@field server ptr_c<wlr_xwayland_server>]]
--[[@field own_server boolean]]
--[[@field xwm ptr_c<wlr_xwm>]]
--[[@field shell_v1 ptr_c<wlr_xwayland_shell_v1>]]
--[[@field cursor ptr_c<wlr_xwayland_cursor>]]
--[[@field display_name string_c]]
--[[@field wl_display ptr_c<wl_display>]]
--[[@field compositor ptr_c<wlr_compositor>]]
--[[@field seat ptr_c<wlr_seat>]]
--[[@field events wlr_xwayland_events]]
--[[@field user_event_handler fun(xwm: ptr_c<wlr_xwm>, event: ptr_c<xcb_generic_event_t>): integer]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_xwayland_events]]
--[[@field ready wl_signal]]
--[[@field new_surface wl_signal]]
--[[@field remove_startup_info wl_signal]]

--[[@class wlr_input_device_type enum]]

--[[@class wlr_input_device]]
--[[@field type wlr_input_device_type]]
--[[@field name string_c]]
--[[@field events wlr_input_device_events]]
--[[@field data ptr_c<unknown>]]

--[[@class wlr_input_device_events]]
--[[@field destroy wl_signal]]

--[[@class wlroots_ffi: { [string]: function }]]
--[[@field wlr_surface_map fun(surface: ptr_c<wlr_surface>)]]
--[[@field wlr_surface_unmap fun(surface: ptr_c<wlr_surface>)]]
--[[@field wlr_surface_reject_pending fun(surface: ptr_c<wlr_surface>, resource: ptr_c<wl_resource>, code: integer, msg: string_c, ...)]]
--[[@field wlr_surface_has_buffer fun(surface: ptr_c<wlr_surface>): boolean]]
--[[@field wlr_surface_state_has_buffer fun(state: ptr_c<wlr_surface_state>): boolean]]
--[[@field wlr_surface_get_texture fun(surface: ptr_c<wlr_surface>): ptr_c<wlr_texture>]]
--[[@field wlr_surface_get_root_surface fun(surface: ptr_c<wlr_surface>): ptr_c<wlr_surface>]]
--[[@field wlr_seat_set_keyboard fun(seat: ptr_c<wlr_seat>, keyboard: ptr_c<wlr_keyboard>);]]
